name: nlp-nschenone
functions:
- url: ../components/get_data.yaml
  name: get-data
- url: ../components/create_data_bunches.yaml
  name: create-data-bunches
- url: ../components/hyper_lm.yaml
  name: hyper-lm
- url: ../components/train_lm.yaml
  name: train-lm
- url: ../components/hyper_clas.yaml
  name: hyper-clas
- url: ../components/train_clas.yaml
  name: train-clas
- url: ../components/model_server.yaml
  name: model-server
- url: ../components/model_server_tester.yaml
  name: model-server-tester
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
