name: nlp-nschenone
functions:
- url: ../components/yaml/get_data.yaml
  name: get-data
- url: ../components/yaml/create_data_bunches.yaml
  name: create-data-bunches
- url: ../components/yaml/hyper_lm.yaml
  name: hyper-lm
- url: ../components/yaml/train_lm.yaml
  name: train-lm
- url: ../components/yaml/hyper_clas.yaml
  name: hyper-clas
- url: ../components/yaml/train_clas.yaml
  name: train-clas
- url: ../components/yaml/model_server.yaml
  name: model-server
- url: ../components/yaml/model_server_tester.yaml
  name: model-server-tester
workflows:
- name: main
  path: workflow.py
artifacts: []
artifact_path: ''
